// Copies the web fonts the pages used to fetch from Google Fonts and cdnfonts
// into assets/fonts/web/, so every page loads them from its own address:
// no visitor IP goes to Google, the CSP can keep fonts to 'self', and no
// third-party stylesheet runs without an integrity check.
//   node scripts/build-fonts.mjs
// Writes assets/fonts/web/{main,mobile,calendar}.css (the same @font-face rules
// Google serves a current Chrome, with local file names) and
// assets/fonts/web/files/*. Re-run only to add a family or weight; then bump ?v=.
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'assets', 'fonts', 'web');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

// One stylesheet per page, with exactly the families and weights that page
// asked Google for before, so nothing renders differently.
const GOOGLE = 'https://fonts.googleapis.com/';
const DIGITAL7 = 'https://fonts.cdnfonts.com/css/digital-7-mono';
const GOOGLE_SANS = GOOGLE + 'css2?family=Google+Sans:wght@400;500;700&display=swap';
const BUNDLES = {
  'main.css': [
    GOOGLE + 'css2?family=Inter:wght@400;500;600;700;800&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap',
    GOOGLE_SANS, DIGITAL7
  ],
  'mobile.css': [
    GOOGLE + 'css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap',
    DIGITAL7
  ],
  'calendar.css': [
    GOOGLE + 'css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;600;700;800&family=DM+Sans:wght@400;500;600;700;800;900&family=DM+Mono:wght@400;500&family=Space+Grotesk:wght@400;600;700;900&family=Space+Mono:wght@400;700&display=swap',
    GOOGLE_SANS, GOOGLE + 'icon?family=Material+Icons+Round', DIGITAL7
  ]
};
// cdnfonts declares two faces under the same name; the browser used the last
// one (the upright "mono"), so only that one is kept. The other Digital-7
// families are not used anywhere.
const KEEP_FACE = (block) => !/Digital-7/.test(block) ||
  (/font-family:\s*'Digital-7 Mono'/.test(block) && /\(mono\)\.woff/.test(block));

const get = async (url, as) => {
  const r = await fetch(url, { headers: { 'user-agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return as === 'buf' ? Buffer.from(await r.arrayBuffer()) : r.text();
};

await rm(out, { recursive: true, force: true });
await mkdir(path.join(out, 'files'), { recursive: true });

const files = new Map();
const local = async (url) => {
  if (!files.has(url)) {
    const ext = path.extname(new URL(url).pathname) || '.woff2';
    const name = createHash('sha256').update(url).digest('hex').slice(0, 16) + ext;
    await writeFile(path.join(out, 'files', name), await get(url, 'buf'));
    files.set(url, `files/${name}?v=1`); // names follow the versioned source URL
  }
  return files.get(url);
};

const header = [
  '/* Generated by scripts/build-fonts.mjs: Google Fonts (OFL / Apache 2.0) and',
  '   Digital-7 Mono (Style-7, free for non-commercial use), served from this site. */'
];
for (const [bundle, sources] of Object.entries(BUNDLES)) {
  const seen = new Set();
  const css = [];
  for (const source of sources) {
    const text = (await get(source)).replace(/\/\*[\s\S]*?\*\//g, '');
    for (const m of text.matchAll(/(@font-face\s*\{[^}]*\}|\.[\w-]+\s*\{[^}]*\})/g)) {
      const rule = m[1].replace(/\s+/g, ' ').trim();
      if (!KEEP_FACE(rule) || seen.has(rule)) continue;
      seen.add(rule);
      let next = rule.replace(/local\([^)]*\),\s*/g, '');
      for (const u of rule.matchAll(/url\(\s*(?:'([^']+)'|"([^"]+)"|([^)'"\s]+))\s*\)/g)) {
        next = next.replace(u[0], `url(${await local(u[1] || u[2] || u[3])})`);
      }
      const [head, body] = next.split(/\s*\{\s*/);
      const decls = body.replace(/\}\s*$/, '').split(';').map((d) => d.trim()).filter(Boolean);
      css.push(`${head} {\n${decls.map((d) => `  ${d};`).join('\n')}\n}`);
    }
  }
  await writeFile(path.join(out, bundle), [...header, ...css, ''].join('\n'));
  console.log(`${bundle}: ${css.length} rules`);
}
console.log(`${files.size} font files`);
